# Project Name
TARGET = Encoder
APP_TYPE = BOOT_SRAM
# Sources
CPP_SOURCES = Encoder.cpp
LDFLAGS = -u _printf_float
# Library Locations
LIBDAISY_DIR = ../../libDaisy/
DAISYSP_DIR = ../../DaisySP/
USE_FATFS = 1
# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
